### ISSUE TITLE
MongoDB connection Pooling

### ISSUE THREAD

**Issue by mtmulch** [mtmulch/Node.js-Angular5-Starter#1]
https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html

Making a connection to the database before any master or workers are created. If the connection is successful do the database seed, then create workers.

**Comment by mtmulch** [comment]
Looking solid, can be adjusts to meet requirements in the future.

**Comment by avidtech** [comment]
I wish I didn't have to do school I'd be doing this instead. Trying to get
my twitch stuff set up more so I can make some money out of it. Not making
any money anywhere and it's starting to be serious.

**Comment by mtmulch** [comment]
Schools more important bro finish that crap up. I'm off the a concert, have a good night!

**Comment by avidtech** [comment]
Right on, have fun. I hate concerts. They freak me out and people get shot
up at them and horrible shit like that lately. Be safe.

**Comment by mtmulch** [comment]
People get shot walking down the street.

**Comment by avidtech** [comment]
? What tonight? Really?

**Comment by mtmulch** [comment]
Lol no just in general, there was no shootings that I know.
