### ISSUE TITLE
Broke The $ global variable.

### ISSUE THREAD

**Issue by mtmulch** [mtmulch/Node.js-Angular5-Starter#27]
Modal isn't working after moving jQuery to angular cli build config.

**Comment by mtmulch** [comment]
Working now on localhost......

**Comment by avidtech** [comment]
Can we schedule a VoIP meeting for all of this? Maybe, two hours max.

Thanks

**Comment by mtmulch** [comment]
Your a VOIP, what are you doing sunday?

**Comment by mtmulch** [comment]
Working in development environment. Will close after I see it work in production.

**Comment by avidtech** [comment]
Prob shit ton of hw

**Comment by mtmulch** [comment]
It's working fine in production, WHATEVER!
